Update buildspec-owasp-zap.yml

diff --git a/buildspec-owasp-zap.yml b/buildspec-owasp-zap.yml
--- a/buildspec-owasp-zap.yml
+++ b/buildspec-owasp-zap.yml
@@ -7,27 +7,26 @@ phases:
     commands:
       - wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
       - tar xvzf ZAP_2.14.0_Linux.tar.gz ZAP_2.14.0/
-      - cd ZAP_2.14.0/
-      - chmod +x ./zap.sh
+      - chmod +x ZAP_2.14.0/zap.sh
       - JAR_NAME=$(basename /home/ec2-user/build/webgoat-2023.6-SNAPSHOT.jar)
-      - DEPLOY_JAR=/home/ec2user/build/$JAR_NAME
-        echo "OWASP Zap analysis status is completed..."; 
+      - DEPLOY_JAR=/home/ec2-user/build/$JAR_NAME
+      - echo "DEPLOY_JAR is set to $DEPLOY_JAR"
+      - echo "OWASP Zap analysis status is completed..."
   build:
     commands: 
       - nohup java -jar "$DEPLOY_JAR" --server.port=8080 --server.address=43.200.16.60 > /dev/null 2> /dev/null < /dev/null &
-      - ./zap.sh -cmd -quickurl http://localhost:8080/WebGoat/ -quickout zap-scan-reports.json -quickprogress
+      - cd /home/ec2-user/build
+      - ./zap.sh -cmd -quickurl http://localhost:8080/WebGoat -quickout zap-scan-reports.json -quickprogress
       - echo "build stage completed"
       - high_alerts=$( cat zap-scan-reports.json | jq -r '.alertsSummary.High')
       - medium_alerts=$( cat zap-scan-reports.json | jq -r '.alertsSummary.Medium')
   post_build:
     commands:
+      - cd /home/ec2-user/build
       - | 
-        jq "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"OWASP-Zap\", \
-        \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
-        \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \
-        \"build_id\": env.CODEBUILD_BUILD_ID, \
-        \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
-        \"report\": . }" zap-scan-results.json > payload.json
-      # if [ $high_alerts -gt 0 ] || [ $medium_alerts -gt 0 ]; then echo "there are high or medium alerts.. failing the build" && exit 1;
+        jq "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"OWASP-Zap\", \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \"build_id\": env.CODEBUILD_BUILD_ID, \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \"report\": . }" zap-scan-reports.json > payload.json
+      # - if [ $high_alerts -gt 0 ] || [ $medium_alerts -gt 0 ]; then
+      #  echo "there are high or medium alerts.. failing the build" && exit 1;
+      #  fi
 artifacts:
-  files: s3://codebuild-test-hbucket/*.json
+  files: /home/ec2-user/build/*.json
