Update buildspec-owasp-zap.yml

diff --git a/buildspec-owasp-zap.yml b/buildspec-owasp-zap.yml
--- a/buildspec-owasp-zap.yml
+++ b/buildspec-owasp-zap.yml
@@ -1,34 +1,31 @@
-#!/bin/bash
-
-# 빌드된 JAR 파일의 경로와 이름 설정
-BUILD_JAR=$(ls /home/ec2-user/build/*.jar)
-JAR_NAME=$(basename $BUILD_JAR)
-echo "> 빌드 파일명: $JAR_NAME" >> /home/ec2-user/deploy.log
-
-# 애플리케이션을 배포할 경로 설정
-DEPLOY_PATH=/home/ec2-user/
-echo "> 빌드 파일 복사" >> /home/ec2-user/deploy.log
-cp $BUILD_JAR $DEPLOY_PATH
-
-# 현재 실행 중인 애플리케이션의 프로세스 ID 확인
-CURRENT_PID=$(pgrep -f $JAR_NAME)
-
-if [ -z $CURRENT_PID ]; then
-  echo "> 현재 구동 중인 애플리케이션이 없으므로 종료하지 않습니다." >> /home/ec2-user/deploy.log
-else
-  echo "> kill -9 $CURRENT_PID"
-  kill -9 $CURRENT_PID
-  sleep 5
-fi
-
-# 배포된 JAR 파일의 경로와 이름 설정
-DEPLOY_JAR=$DEPLOY_PATH/$JAR_NAME
-echo "> DEPLOY_JAR 배포" >> /home/ec2-user/deploy.log
-
-# 기존의 Java 애플리케이션 실행 명령
-nohup java -jar $DEPLOY_JAR >> /home/ec2-user/deploy.log 2>/home/ec2-user/deploy_err.log &
-
-# 서버 실행 명령
-echo "> 서버 실행" >> /home/ec2-user/deploy.log
-nohup java -jar "$DEPLOY_JAR" --server.port=8080 --server.address=43.200.16.60 > /dev/null 2> /dev/null < /dev/null &
-# nohup $JAVA_HOME/bin/java -jar $DEPLOY_PATH/webgoat-2023.6-SNAPSHOT.jar >> /home/ec2-user/deploy.log 2>/home/ec2-user/deploy_err.log &
+version: 0.2
+phases:
+  install:
+    commands:
+      - echo "install phase....."
+  pre_build:
+    commands:
+      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2_14_0_unix.sh -O zap.sh
+      - chmod +x ./zap.sh
+      - JAR_NAME=$(basename /home/ec2-user/build/webgoat-2023.6-SNAPSHOT.jar)
+        echo "OWASP Zap analysis status is completed..."; 
+  build:
+    commands: 
+      - nohup java -jar "$DEPLOY_JAR" --server.port=8080 --server.address=43.200.16.60 > /dev/null 2> /dev/null < /dev/null &
+      - sh ./zap.sh -cmd -quickurl http://localhost:8080/WebGoat -quickout zap-scan-reports.json -quickprogress
+      - echo "build stage completed"
+      - high_alerts=$( cat zap-scan-reports.json | jq -r '.alertsSummary.High')
+      - medium_alerts=$( cat zap-scan-reports.json | jq -r '.alertsSummary.Medium')
+  post_build:
+    commands:
+      - | 
+        jq "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"OWASP-Zap\", \
+        \"createdAt\": $(date +\"%Y-%m-%dT%H:%M:%S.%3NZ\"), \"source_repository\": env.CODEBUILD_SOURCE_REPO_URL, \
+        \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \
+        \"build_id\": env.CODEBUILD_BUILD_ID, \
+        \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
+        \"report\": . }" zap-scan-results.json > payload.json
+      - if [ $high_alerts -gt 0 ] || [ $medium_alerts -gt 0 ]; then echo "there are high or medium alerts.. failing the build" && exit 1; else exit 0; fi
+artifacts:
+  type: zip
+  files: s3://codebuild-test-hbucket/*.json
