Update Semgrep.yml

diff --git a/.github/workflows/Semgrep.yml b/.github/workflows/Semgrep.yml
--- a/.github/workflows/Semgrep.yml
+++ b/.github/workflows/Semgrep.yml
@@ -1,9 +1,6 @@
 name: Semgrep
-
 on:
   push:
-
-
 jobs:
   semgrep:
     # User-definable name of this GitHub Actions job:
@@ -14,7 +11,6 @@ jobs:
     container:
       # A Docker image with Semgrep installed. Do not change this.
       image: returntocorp/semgrep
-
     steps:
       # Fetch project source with GitHub Actions Checkout.
       - uses: actions/checkout@v3
@@ -26,3 +22,26 @@ jobs:
            # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable. 
           # SEMGREP_RULES: p/default # more at semgrep.dev/explore
            SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }} 
+      - name: Snyk SCA Scanning
+        continue-on-error: true
+        run: |   
+         Semgrepcount=$(curl -X GET --header 'Content-Type: application/json' --header 'Authorization: token ${{ secrets.SEMGREP_APP_TOKEN }}' 'https://semgrep.dev/api/v1/deployments/severities/findings')
+         HIGH=$(echo "$Semgrepcount" | jq .issueCountsBySeverity.high )
+         MEDIUM=$(echo "$Semgrepcount" | jq .issueCountsBySeverity.medium )
+         LOW=$(echo "$Semgrepcount" | jq .issueCountsBySeverity.low )
+         echo "HIGH = $HIGH"
+         echo "MEDIUM = $MEDIUM"
+         echo "LOW = $LOW"
+         if [ $CRITICAL -gt 0 ]
+         then
+           curl -H 'Content-Type: application/json' -d '{"text": "<Application Name> has Critical Issues in Semgrep"}'         
+           echo "##[error]Application has critical issues"
+           #exit 1
+         elif [ $HIGH -gt 0 ]
+         then
+           curl -H 'Content-Type: application/json' -d '{"text": "<Application Name> has High Issues in Semgrep"}'         
+           echo "##[error]Application has High issues"
+           #exit 1
+         else
+          echo "PASSED"
+         fi
